### ISSUE TITLE
Add support for custom jobID

### ISSUE THREAD

**Issue by microsoftly** [mattn/goveralls#122]
Currently, the only way jobID is selected is by searching through possible env vars that my exist for different build tools. In circleCI its possible to have multiple jobs run in parallel for a given workflow, each with their own unique buildID. It should be possible to submit parallel reports for each, but this restriction prevents it.

An example workflow would be:
```yml
workflows:
  version: 2
  tests:
    jobs:
      - unit-test
      - integration-test
      - end-to-end-test
      - report-coverage:
          requires:
            - unit-test
            - integration-test
            - end-to-end-test
```
where `report-coverage` is just the `curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_TOKEN -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"` call. If a custom ID could be provided, this would allow us to aggregate across all jobs that run in parallel.
