### ISSUE TITLE
Exit 1 with no output on travis-ci with go1.14

### ISSUE THREAD

**Issue by daniel-nichter** [mattn/goveralls#182]
Example: https://travis-ci.org/github/go-cmd/cmd/jobs/740620242

But the [same build on go1.13](https://travis-ci.org/github/go-cmd/cmd/jobs/740620241) works fine.

.travis.yml:

```yaml
language: go
sudo: false

os:
  - linux
  - windows

go:
  - "1.13"
  - "1.14"

before_install:
  - go mod vendor
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -race -show -debug
```
Also originally had `-path github.com/go-cmd/cmd` but removed to see if that made a difference (it didn't).

No output even with `-debug` seems to suggest it's not even running?
