### ISSUE TITLE
Unable to run on multiple packages

### ISSUE THREAD

**Issue by usmanismail** [mattn/goveralls#20]
I am unable to use this tool with multiple packages

goveralls -package ./... XXXXXXXXXXXX
cannot use test profile flag with multiple packages
error: %v exit status 1
17:58:08 gocov.go:132: Error loading gocov results: exit status 1

**Comment by keighl** [comment]
Thanks for writing gover, @modocache. Here's a travis config that works for one of my projects with 'sub-packages'. `go test` can't output multiple coverprofiles, but it's easy enough to just run it a few times.  

```yml
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=api.coverprofile ./api
  - go test -coverprofile=utils.coverprofile ./utils
  - go test -coverprofile=models.coverprofile ./models
  - go test -coverprofile=main.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
```
