### ISSUE TITLE
coverage:unknown badge even after successful execution in Github Actions

### ISSUE THREAD

**Issue by ambiknai** [mattn/goveralls#202]
Hi

I have below github actions which executed without any error

```
name: Quality
on: [push, pull_request]
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        go test $(go list ./... | grep -v /vendor/ | grep -v /cmd | grep -v /tests) -race -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      env:
        GOPATH: ${{ github.workspace }}
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      run: $GOPATH/bin/goveralls -coverprofile=covprofile -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: ${{ github.workspace }}
      
 ```

Job Run: https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/27/checks?check_run_id=3359889644

But the coverage badge is grey and unknown status.
