### ISSUE TITLE
github service error: Couldn't find a repository matching this job

### ISSUE THREAD

**Issue by avelino** [mattn/goveralls#203]
without `-service`:
```sh
goveralls -repotoken $COVERALLS_TOKEN -coverprofile=coverage.out -race -covermode atomic -v      
Job ##392.5
https://coveralls.io/jobs/86151961
```

with `-service`:
```sh
goveralls -repotoken $COVERALLS_TOKEN -coverprofile=coverage.out -race -covermode atomic -v -service=github
bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
goveralls -repotoken $COVERALLS_TOKEN -coverprofile=coverage.out -race -covermode atomic -v -service github
bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
```

**Comment by shogo82148** [comment]
use `${{ secrets.GITHUB_TOKEN }}` instead of COVERALLS_TOKEN 

https://github.com/mattn/goveralls#github-actions

```yaml
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
```
