### ISSUE TITLE
Comment Job execution link as a comment to the PR

### ISSUE THREAD

**Issue by leonardpahlke** [mattn/goveralls#211]
Hi 👋

Great Action! Thanks :)

I integrated it to my workflow and it works great. I am trying to comment into the PR chat the link to the codecoverage website. Maybe this could be a nice addition for this too.

Code except 

```yaml

    - name: Send coverage
      id: send-coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        goveralls -coverprofile=covprofile -service=github > code_coverage_link
        coverage="$(cat code_coverage_link)"
        echo "::set-output name=coverage::$coverage"
     
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        token: ${{secrets.GOVERNANCE_BOT_TOKEN}}
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'carbonautMustache'
        body-includes: Code coverage link

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{secrets.GOVERNANCE_BOT_TOKEN}}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Code coverage link: ${{ steps.send-coverage.outputs.coverage }}
        edit-mode: replace

```

I am unable to retrieve the link and only get this output: 'Code coverage link: Job #2250989753.1' no idea how to get the website link.. I looked into the API defenition but could find a way to http request it. 

The link is printed to the action execution but I am unable to store it in a variable..

Any ideas? Thanks! 

I am happy to document this in this repo's readme if that's interesting

Cheers Leo

**Comment by leonardpahlke** [comment]
cc @mattn

**Comment by mattn** [comment]
Interesting. Could you please send me PR to modify README ?

**Comment by shogo82148** [comment]
I recommend you to enable "Leave comments?" options on coveralls, instead of adding "Create or update comment" step.

e.g. the setting for https://github.com/shogo82148/actions-goveralls is available on https://coveralls.io/github/shogo82148/actions-goveralls/settings:

![image](https://user-images.githubusercontent.com/1157344/166148229-9ee02c6e-79be-43da-93b6-6cdbad03dfba.png)

The example of coveralls' comments is here: https://github.com/shogo82148/actions-goveralls/pull/352#issuecomment-1113503480

**Comment by leonardpahlke** [comment]
Yes! I can create a "work in progress" / WIP PR but as I said it does not work quite yet.. 


I get `Code coverage link: Job #2253645797.1` as a comment but it should be `Code coverage link: https://coveralls.io/jobs/98738866`
![image](https://user-images.githubusercontent.com/58054077/166148450-cd51a2fb-f7ec-4e90-897f-c2e74f587bc1.png)

**Comment by shogo82148** [comment]
Or you want to do this in your GitHub Actions workflow, you should use `2> code_coverage_link` instead of `> code_coverage_link`.

The "Send coverage" will be:

```bash
goveralls -coverprofile=covprofile -service=github 2> code_coverage_link
coverage="$(cat code_coverage_link)"
echo "::set-output name=coverage::$coverage"
```

**Comment by leonardpahlke** [comment]
Thanks for your help :) `2>` does not solve the problem for me :thinking: .. The comment you posted before with the [comment that gets posted](https://github.com/shogo82148/actions-goveralls/pull/352#issuecomment-1113503480), looks great and is actually is exactly what I like to achieve! Great that this is already implemented.

The settings on https://coveralls.io/github/<user/org>/<repo>/settings are already configured.  The comment does not appear tho. coveralls is authenticated as OAuth and should have access.. Do you know what could be missing to

**Comment by leonardpahlke** [comment]
okay I figured it out.. I will open a PR soon to update the README. The problem is that passing a multi line string through github action outputs is a bit weird,, (see [article](https://trstringer.com/github-actions-multiline-strings/))

This version works for me now :) 
```yaml
    - name: Send coverage
      id: send-coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        CODE_COVERAGE_LINK=$(goveralls -coverprofile=covprofile -service=github)
        coverage=$(echo $CODE_COVERAGE_LINK)
        echo "::set-output name=coverage::$coverage"

    - name: Step
      run: echo $CODE_COVERAGE_LINK

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        token: ${{secrets.GOVERNANCE_BOT_TOKEN}}
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'carbonautMustache'
        body-includes: Code coverage link

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{secrets.GOVERNANCE_BOT_TOKEN}}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Code coverage link: ${{ steps.send-coverage.outputs.coverage }}
        edit-mode: replace
```
